### ISSUE TITLE
Support to ES 1.6

### ISSUE THREAD

**Issue by RoxasShadow** [honeypotio/searchspot#42]
As many providers still provide ES 1.6 by default and we are able to still give support for it, I'm not sure why we have decided to delete the `es-1.6` branch, making also dead the link to it in `README.md`.

I agree that having a separate branch for 1.6 is not ideal, but we can spend some little effort in order to add feature switch for the versioning of the ES dependencies.

**Comment by kdamball** [comment]
@RoxasShadow Can you push the branch by any chance?

**Comment by RoxasShadow** [comment]
@kdamball I guess @duksis did it already. Closing here, thanks 👍
